core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('user/', include('user.urls', namespace = 'user')),
    path('members_area/', include('members_area.urls', namespace = 'members_area'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import *


app_name = 'home'
urlpatterns = [
    path('', home_page, name="home_page"),
    path('for_parents/', for_parents, name="for_parents"),
    path('for_children/', for_children, name="for_children"),
    path('about/', about, name="about"),
    path('news/<int:id>/', one_news, name='one_news'),
    path('events/<int:id>/', one_event, name='one_event')
]

home/models.py
from django.db import models
import os


def save_news_img(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_'{instance.date}.{extension}"
	
	return  os.path.join('news/', new_filename) 


def save_events_img(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_'{instance.date}.{extension}"
	
	return  os.path.join('events/', new_filename) 


def save_logo(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.name}.{extension}"
	
	return  os.path.join('logos/', new_filename)


def save_info_img(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_info'.{extension}"
	return  os.path.join('info/', new_filename)



class News(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	date = models.DateField(auto_now_add=True)
	image = models.ImageField(upload_to=save_news_img)

	
class Events(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	date = models.DateField(auto_now_add=True)
	image = models.ImageField(upload_to=save_events_img, blank=True)


class HomePage(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	image = models.ImageField(upload_to=save_info_img, blank=True)


class HomePageInfos(models.Model):
	title = models.CharField(max_length=255, blank=True)
	text = models.TextField( blank=True)
	image = models.ImageField(upload_to=save_info_img, blank=True)


class Partner(models.Model):
	name = models.CharField(max_length=255, blank=True)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to=save_logo, blank=True)


class AboutPage(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	image = models.ImageField(upload_to=save_info_img, blank=True)


class AboutPageInfos(models.Model):
	title = models.CharField(max_length=255, blank=True)
	text = models.TextField( blank=True)
	image = models.ImageField(upload_to=save_info_img, blank=True)


class ChildrenPage(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	image = models.ImageField(upload_to=save_info_img, blank=True)


class ChildrenPageInfos(models.Model):
	title = models.CharField(max_length=255, blank=True)
	text = models.TextField( blank=True)
	image = models.ImageField(upload_to=save_info_img, blank=True)


class ParentPage(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	image = models.ImageField(upload_to=save_info_img, blank=True)


class ParentPageInfos(models.Model):
	title = models.CharField(max_length=255, blank=True)
	text = models.TextField( blank=True)
	image = models.ImageField(upload_to=save_info_img, blank=True)


class SocialMediaUrls(models.Model):
	instagram = models.URLField(max_length=255, blank=True)
	facebook = models.URLField(max_length=255,  blank=True)
	twitter = models.URLField(max_length=255, blank=True)

home/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import *
# Create your views here.


def home_page(request):
	home_info = HomePage.objects.all()
	main_info = HomePageInfos.objects.all()
	news = News.objects.all()
	events = Events.objects.all()
	socials = SocialMediaUrls.objects.all()
	print(main_info.first)
	return render(request, 'home/home_page.html',{'home_info': home_info,
		'news':news, 'events': events, 'socials':socials, 'main_info':main_info})


def one_news(request, id):
	one_news = get_object_or_404(News, pk=id)
	return render(request, 'home/one_news.html',{'one_news': one_news})


def one_event(request, id):
	one_event = get_object_or_404(Events, pk=id)
	return render(request, 'home/one_event.html',{'one_event': one_event})


def about(request):
	about_info = AboutPage.objects.all()
	main_info = AboutPageInfos.objects.all()
	partners = Partner.objects.all()
	return render(request, 'about.html', {'about_info': about_info, 'partners': partners, 'main_info':main_info})


def for_parents(request):
	parents_info = ParentPage.objects.all()
	main_info = ParentPageInfos.objects.all()
	return render(request, 'for-parents.html', {'parents_info': parents_info, 'main_info':main_info})


def for_children(request):
	children_info = ChildrenPage.objects.all()
	main_info = ChildrenPageInfos.objects.all()
	return render(request, 'for-children.html', {'children_info': children_info, 'main_info':main_info})




home/templates/home/home_page.html
{% extends 'index.html' %}
{% load static  %}

{% block topcontent %}
<header class="main-header-back-img" style="background-image: url('{{ main_info.last.image.url }}');">
    <div class="container-lg padding-for-header-text">
        <div class="header-text">
            <h1 class="text-light">{{ main_info.last.title }}</h1>
            <h5 class="text-light">{{ main_info.last.text }}</h5>
        </div>
    </div>
</header>
{% endblock %}

{% block maincontent %}

    {% for info in home_info %}
    {% if forloop.counter|divisibleby:2 %}
           <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 order-sm-2 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 order-sm-1 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    {% else %}
        <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endif %}
    
    {% endfor %}
{% endblock %}
{% block eventscontent %}
<div class="container-lg">
    <h2 class="events-tile">Events</h2>
    <div class="row">
        {% for event in events %}
        <div class="col-lg-12">
            <div class="card card-margin">
                <div class="card-body pt-">
                    <div class="widget-49">
                        <div class="widget-49-title-wrapper">
                            <div class="widget-49-meeting-info">
                                <h5 class="widget-49-pro-title">{{event.title}}</h5>
                            </div>
                        </div>
                        <div class="widget-49-title-wrapper">
                            <p class="widget-49-meeting-info">{{event.description|slice:200}} ...</p>
                        </div>
                        <div class="widget-49-meeting-action">
                            <a href="{% url 'home:one_event' event.id %}" class="btn btn-sm btn-flash-border-primary">Read</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block newscontent %}
<div class="container-lg">
    <h2 class="news-tile">News</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for one_news in news %}
        <div class="col">
            <div class="card h-100">
                {% if one_news.image %}
                <img src="{{one_news.image.url}}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{one_news.title}}</h5>
                    <p class="card-text">{{one_news.description|slice:300}} ...</p>
                </div>
                <div class="card-footer">
                    <div class="widget-49-meeting-action">
                        <a href="{% url 'home:one_news' one_news.id %}"
                           class="btn btn-sm btn-flash-border-primary">Read</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

        {% block socials %}
        <ul class="nav col justify-content-center justify-content-lg-start list-unstyled d-flex">
            <li class="ms-3"><a class="text-dark" href="{{socials.first.facebook}}"><i class="bi bi-facebook h3"></i></a></li>
            <li class="ms-3"><a class="text-dark" href="{{socials.first.instagram}}"><i class="bi bi-instagram h3"></i></a></li>
            <li class="ms-3"><a class="text-dark" href="{{socials.first.twitter}}"><i class="bi bi-twitter-x h3"></i></a></li>
        </ul>
        {% endblock %}

home/templates/home/one_event.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
{% endblock %}
{% block maincontent %}
<section class="one-event">
    <div class="container-lg">
        <div class="d-flex row gy-3 gy-md-4 gy-lg-0">
            <div class="order-sm-2 col-12 col-lg-6 col-xl-5">
                {% if one_event.image %}
                <img class="img-fluid rounded" loading="lazy" src="{{one_event.image.url}}" alt="event">
                {% endif %}
            </div>
            <div class="order-sm-1 col-12 col-lg-6 col-xl-7">
                <div class="row justify-content-start">
                    <div class="col-12 col-xl-11">
                        <h2 class="mb-3">{{one_event.title}}</h2>
                        <p>{{one_event.description}}</p>
                        <p>{{one_event.date}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}
{% endblock %}

{% block extracontent %}

{% endblock %}

home/templates/home/one_news.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
{% endblock %}
{% block maincontent %}
<section class="one-news">
    <div class="container-lg">
        <div class="d-flex row gy-3 gy-md-4 gy-lg-0">
            <div class="col-12 col-lg-6 col-xl-7">
                <div class="row justify-content-start">
                    <div class="col-12 col-xl-11">
                        <h2 class="mb-3">{{one_news.title}}</h2>
                        <p>{{one_news.description}}</p>
                        <p class="text-black-50">{{one_news.date}}</p>
                    </div>
                </div>
            </div>
            {% if one_news.image %}
            <h6>Photo:</h6>
            <div class="col-12 col-lg-6 col-xl-5">
                <img class="img-fluid rounded" loading="lazy" src="{{one_news.image.url}}" alt="News">
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}