core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('user/', include('user.urls', namespace = 'user')),
    path('members_area/', include('members_area.urls', namespace = 'members_area'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from .views import *
from django.contrib.auth import views as auth_views


app_name = 'user'
urlpatterns = [
    path('registration/', registration, name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home:home_page'), name='logout'),
]


user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
	pass

user/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','style': 'width: 100%;'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','style': 'width: 100%;'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','style': 'width: 100%;'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control','style': 'width: 100%;'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control','style': 'width: 100%;'}))
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput(attrs={'class': 'form-control','style': 'width: 100%;'}))


    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2',)


class LoginForm(AuthenticationForm):
    username = UsernameField(label="Username",widget=forms.TextInput(attrs={
        'class': 'form-control','style': 'width: 100%;'
        }))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control','style': 'width: 100%;'
        }))

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import login

from .forms import *


# Create your views here.
def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home:home_page')
    else:
        form = RegistrationForm()
    return render(request, 'user/registration.html', {'form': form})
    # if request.method == 'POST':
    #     form = RegistrationForm(request.POST)
    #     if form.is_valid():
    #         user = form.save(commit=False)
    #         form.save()
    #         user = form.cleaned_data.get('username')
    #         messages.success(request, 'Account was created for ' + user)
    #         return redirect('user:login')
    # else:
    #     form = RegistrationForm()

    # return render(request, 'user/registration.html', {form:'form'})


class UserLoginView(LoginView):
    template_name = 'user/login.html'
    authentication_form = LoginForm

    def get_success_url(self):
        return reverse_lazy('members_area:member_page') 
    

user/templates/user/login.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
{% endblock %}
{% block maincontent %}
 <main class="content">
    <section class="login">
      <div class="container-lg">
        <div class="row justify-content-center">
          <div class="col-lg-4">
              <h2 class="title">Login</h2>
              {% if form.errors %}
                <br>
                <p>Your username and password didn't match. Please try again.</p>
                <br>
              {% endif %}
                
              <form class="login-form" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <p>{{field.label_tag }}</p>
                <p> {{field }}</p>
                {% endfor %}
                <button class="btn btn-outline-dark mb-4" type="submit">Login</button>
              </form>
              
              <div class="login-text">
                <div>Don't have an account?
                <a class="a-link" href="{% url 'user:registration' %}">Register</a>
                </div>
              </div>
          </div>
        </div>
      </div>
    </section>
    </main>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}

user/templates/user/registration.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
{% endblock %}
{% block maincontent %}
 <main class="content">
    <div class="container-lg">
      <div class="row justify-content-center">
        <div class="col-lg-4">
            <section class="login">
              <h2 class="title">Registration</h2>
              <form class="login-form" method="POST">
                {% csrf_token %}
                {% if form.errors %}
                    {% for error in field.errors %}
                    <strong>{{ error|escape }}</strong>
                    <strong>{{ field|escape }}</strong>
                    {% endfor %}
                {% endif %}
                {% for field in form %}
                    <p>{{field.label_tag }}</p>
                    <p> {{field }}</p>
                {% endfor %}
                <button class="btn btn-outline-dark mb-4" type="submit">
                    Create Account
                </button>

                </form>
              <div class="login-text">
                <p>Already have an account?</p>
                <a class="a-link" href="{% url 'user:login' %}">Login</a>
              </div>
            </section>
          </div>
        </div>
      </div>
    </main>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}