core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('user/', include('user.urls', namespace = 'user')),
    path('members_area/', include('members_area.urls', namespace = 'members_area'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

members_area/urls.py
from django.urls import path

from .views import *


app_name = 'members_area'
urlpatterns = [
    path('membersarea', member_page, name='member_page'),
    path('membersarea/news/<int:id>/', one_news, name='one_news'),
    path('membersarea/events/<int:id>/', one_event, name='one_event'),
    path('membersarea/download/<int:file_id>',download_file, name='download_file')
    
]

members_area/models.py
from django.db import models
import os


def save_main_img(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_Info'.{extension}"
	return  os.path.join('members_info/', new_filename) 


def save_mnews_img(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_'{instance.date}.{extension}"
	return  os.path.join('members_news/', new_filename) 


def save_mevents_img(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_'{instance.date}.{extension}"
	return  os.path.join('members_events/', new_filename) 


def save_mevents_files(instance, filename):
	extension = filename.split('.')[-1]
	new_filename = f"{instance.title}'_CSresource'.{extension}"
	return  os.path.join('members_resources/', new_filename) 


class MembersPageInfos(models.Model):
	title = models.CharField(max_length=255, blank=True)
	text = models.TextField( blank=True)
	image = models.ImageField(upload_to=save_main_img, blank=True)


class MembersNews(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	date = models.DateField(auto_now_add=True)
	image = models.ImageField(upload_to=save_mnews_img)

	
class MembersEvents(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	date = models.DateField(auto_now_add=True)
	image = models.ImageField(upload_to=save_mevents_img, blank=True)


class MembersResources(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField(blank=True)
	date = models.DateField(auto_now_add=True)
	files = models.FileField(upload_to=save_mevents_files)


class MembersMessage(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	date = models.DateField(auto_now_add=True)




members_area/forms.py
from django import forms 
from .models import MembersMessage


class MessageForm(forms.ModelForm):
	class Meta:
		model = MembersMessage
		fields = ['title', 'text',]
		widgets = {
			'title': forms.TextInput(attrs={'label': 'Title1', 'style': 'width: 100%;',}),
		    'text': forms.Textarea(attrs={'label': 'Text', 'style': 'width: 100%;', "rows": 10}),
		}

members_area/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth.decorators import login_required
from django.http import FileResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages


from .models import *
from .forms import *


@login_required
def member_page(request):
	form = MessageForm()
	main_info = MembersPageInfos.objects.all()
	member_news = MembersNews.objects.all()
	member_events = MembersEvents.objects.all()
	resources = MembersResources.objects.all()
	context = {'m_news':member_news, 'm_events': member_events, 'resources':resources,
				'message_form': form,'main_info':main_info}
	# return render(request, 'members_area/member_page.html',context)

	if request.method == 'POST': # If the form has been submitted...
		form = MessageForm(request.POST) # A form bound to the POST data
		if form.is_valid():# All validation rules pass
			data = form.cleaned_data
			member_msg = MembersMessage(title=data['title'],text=data['text'])
			member_msg.save()
			messages.success(request, 'Your message has been sent!')
			return redirect('members_area:member_page')
	else:
		return render(request, 'members_area/member_page.html',context)


@login_required
def one_news(request, id):
	one_news = get_object_or_404(MembersNews, pk=id)
	return render(request, 'members_area/one_news.html',{'one_news': one_news})


@login_required
def one_event(request, id):
	one_event = get_object_or_404(MembersEvents, pk=id)
	return render(request, 'members_area/one_event.html',{'one_event': one_event})


@login_required
def download_file(request, file_id):
	get_file = get_object_or_404(MembersResources, pk=file_id)
	file_path = get_file.files.path
	filename_extension = 1
	response = FileResponse(get_file.files, as_attachment=True, )
	return response


members_area/templates/members_area/member_page.html
{% extends 'index.html' %}
{% load static  %}
{% block topcontent %}
<header class="main-header-back-img" style="background-image: url('{{ main_info.last.image.url }}');">
    <div class="container-lg padding-for-header-text">
        <div class="header-text">
            <h1 class="text-light">{{ main_info.last.title }}</h1>
            <h5 class="text-light">{{ main_info.last.text }}</h5>
        </div>
    </div>
</header>
{% endblock %}
{% block maincontent %}
<section class="resources">
    <div class="container-lg mb-5 mt-5 pt-5">
        <h2 class="res-tile">Resources and Files</h2>
        <div class="row">
            {% for resource in resources %}
            <div class="col-lg-12">
                <div class="card card-margin">
                    <div class="card-body">
                        <div class="row">
                            <div class="col align-content-center">
                                <span>{{resource.title}}</span>
                            </div>
                            <div class="col d-flex justify-content-end">
                                <a href="{% url 'members_area:download_file' resource.id %}" class="btn btn-outline-dark">Download</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}
{% block eventscontent %}
<div class="container-lg">
    <h2 class="events-tile">Events for you</h2>
    <div class="row">
        {% for event in m_events %}
        <div class="col-lg-12">
            <div class="card card-margin">
                <div class="card-body pt-">
                    <div class="widget-49">
                        <div class="widget-49-title-wrapper">
                            <div class="widget-49-meeting-info">
                                <h5 class="widget-49-pro-title">{{event.title}}</h5>
                            </div>
                        </div>
                        <div class="widget-49-title-wrapper">
                            <p class="widget-49-meeting-info">{{event.description|slice:100}}</p>
                        </div>
                        <div class="widget-49-meeting-action">
                            <a href="{% url 'members_area:one_event' event.id %}" class="btn btn-sm btn-flash-border-primary">Read</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block newscontent %}
<div class="container-lg">
    <h2 class="news-tile">News for you</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for one_news in m_news %}
        <div class="col">
            <div class="card h-100">
                {% if one_news.image %}
                <img src="{{one_news.image.url}}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{one_news.title}}</h5>
                    <p class="card-text">{{one_news.description|slice:300}}</p>
                </div>
                <div class="card-footer">
                    <div class="widget-49-meeting-action">
                        <a href="{% url 'members_area:one_news' one_news.id %}"
                           class="btn btn-sm btn-flash-border-primary">Read</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block extracontent %}
<section class="contact">
    <div class="container-lg">
        <h2>Do you have any questions?</h2>
        <h4>Fill that form to send your questions to our admin</h4>
        <div class="col-lg-4 pt-4">
            <form id="message_form" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="inputTitle" class="form-label">Title</label>
                    <input type="email" class="form-control" id="inputTitle">
                </div>
                <div class="mb-3">
                    <label for="textArea" class="form-label">Text</label>
                    <textarea class="form-control" id="textArea" rows="3"></textarea>
                </div>
                <button type="submit" form="message_form" value="Submit" class="btn btn-outline-dark">Submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}
<!-- {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                <h4 class="alert-success text-center" style="padding-top: 5px; padding-bottom: 5px;">
                    {{ message }}
                </h4>
            </li>
        {% endfor %}
     </ul>
 {% endif %} -->

members_area/templates/members_area/one_news.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
{% endblock %}
{% block maincontent %}
<section class="one-news">
  <div class="container-lg">
    <div class="d-flex row gy-3 gy-md-4 gy-lg-0">
      <div class="col-12 col-lg-6 col-xl-7">
        <div class="row justify-content-start">
          <div class="col-12 col-xl-11">
            <h2 class="mb-3">{{one_news.title}}</h2>
            <p>{{one_news.description}}</p>
            <p class="text-black-50">{{one_news.date}}</p>
          </div>
        </div>
      </div>
      {% if one_news.image %}
      <h6>Photo:</h6>
      <div class="col-12 col-lg-6 col-xl-5">
        <img class="img-fluid rounded" loading="lazy" src="{{one_news.image.url}}" alt="News">
      </div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}