core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('user/', include('user.urls', namespace = 'user')),
    path('members_area/', include('members_area.urls', namespace = 'members_area'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import *


app_name = 'home'
urlpatterns = [
    path('', home_page, name="home_page"),
    path('for_parents/', for_parents, name="for_parents"),
    path('for_children/', for_children, name="for_children"),
    path('about/', about, name="about"),
    path('news/<int:id>/', one_news, name='one_news'),
    path('events/<int:id>/', one_event, name='one_event')
]

members_area/urls.py
from django.urls import path

from .views import *


app_name = 'members_area'
urlpatterns = [
    path('membersarea', member_page, name='member_page'),
    path('membersarea/news/<int:id>/', one_news, name='one_news'),
    path('membersarea/events/<int:id>/', one_event, name='one_event'),
    path('membersarea/download/<int:file_id>',download_file, name='download_file')
    
]

user/urls.py
from django.urls import path

from .views import *
from django.contrib.auth import views as auth_views


app_name = 'user'
urlpatterns = [
    path('registration/', registration, name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home:home_page'), name='logout'),
]


templates/about.html
{% extends 'index.html' %}
{% load static  %}

{% block topcontent %}
<header class="main-header-back-img" style="background-image: url('{{ main_info.last.image.url }}');">
    <div class="container-lg padding-for-header-text">
        <div class="header-text">
            <h1 class="text-light">{{ main_info.last.title }}</h1>
            <h5 class="text-light">{{ main_info.last.text }}</h5>
        </div>
    </div>
</header>
{% endblock %}

{% block maincontent %}

<main>
    {% for info in about_info %}
    {% if forloop.counter|divisibleby:2 %}
           <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 order-sm-2 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 order-sm-1 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    {% else %}
        <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endif %}
    
    {% endfor %}
    <section class="partners">
        <div class="container-lg mt-5">
            <h2 class="partners-tile">Our partners</h2>
             <div class="row">
            {% for partner in partners %}
                <div class="col-4 col-lg-2 text-center">
                    {% if partner.image %}
                    <img src="{{ partner.image.url }}" class="img-thumbnail img-fluid border border-0 rounded rounded-4" alt="...">
                    {% endif %}
                    {% if partner.name %}
                    <h4 class="card-title pt-3 pb-3 text-secondary">{{ partner.name }}</h4>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}

templates/for-children.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
<header class="main-header-back-img for-children-back-img">
    <div class="container-lg padding-for-header-text">
        <div class="header-text bg-white">
            <h1 class="text-dark">Cybersecurity for children</h1>
            <h5 class="text-dark">Website for growing your knowledge about security in digital age</h5>
        </div>
    </div>
</header>
{% endblock %}
{% block maincontent %}

<main>
    {% for info in children_info %}
    {% if forloop.counter|divisibleby:2 %}
           <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 order-sm-2 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 order-sm-1 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    {% else %}
        <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endif %}
    
    {% endfor %}

</main>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}

templates/for-parents.html
{% extends 'index.html' %}
{% load static  %}


{% block topcontent %}
<header class="main-header-back-img" style="background-image: url('{{ main_info.last.image.url }}');">
    <div class="container-lg padding-for-header-text">
        <div class="header-text">
            <h1 class="text-dark">{{ main_info.last.title }}</h1>
            <h5 class="text-dark">{{ main_info.last.text }}</h5>
        </div>
    </div>
</header>
{% endblock %}
{% block maincontent %}

<main>
    {% for info in parents_info %}
    {% if forloop.counter|divisibleby:2 %}
           <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 order-sm-2 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 order-sm-1 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    {% else %}
        <section class="about py-3 py-md-5">
        <div class="container-lg">
            <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
                <!--add order-sm-2 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-5">
                    {% if info.image %}
                    <img class="img-fluid rounded" loading="lazy" src="{{info.image.url}}" alt="About 1">
                    {% endif %}
                </div>
                <!--add order-sm-1 to next div to swap img and text-->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="row justify-content-xl-center">
                        <div class="col-12 col-xl-11">
                            <h2 class="mb-3">{{ info.title }}</h2>
                            <p class="mb-5">{{ info.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endif %}
    
    {% endfor %}
</main>
{% endblock %}
{% block eventscontent %}

{% endblock %}

{% block newscontent %}

{% endblock %}

{% block extracontent %}

{% endblock %}

templates/index.html
<html lang="en" class="h-100">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cybersecurity AIU</title>
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <!--    bootsrap from internet-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!--    icons from internet-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="d-flex flex-column h-100">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-lg">
        <a class="navbar-brand justify-content-lg-center" href="{% url 'home:home_page' %}">Cybersecurity</a>
        <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-content-lg-center">
                <li class="nav-item align-content-lg-center">
                    <a class="nav-link" aria-current="page" href="{% url 'home:home_page' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item align-content-lg-center">
                    <a class="nav-link" href="{% url 'members_area:member_page' %}">Members Area</a>
                </li>
                {% else %}
                <li class="nav-item align-content-lg-center">
                    <a class="nav-link" href="{% url 'user:login' %}">Members Area</a>
                </li>
                {% endif %}
                <li class="nav-item align-content-lg-center">
                    <a class="nav-link" href="{% url 'home:for_parents' %}">For Parents</a>
                </li>
                <li class="nav-item align-content-lg-center">
                    <a class="nav-link" href="{% url 'home:for_children' %}">For Children</a>
                </li>
                <li class="nav-item align-content-lg-center">
                    <a class="nav-link" href="{% url 'home:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item align-content-lg-center">
                    {% csrf_token %}
                    <form action="{% url 'user:logout' %}" method="post" class="mb-0">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-dark ps-lg-2 pe-lg-2 ms-lg-5">
                            Log Out
                        </button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item align-content-lg-center">
                    <a href="{% url 'user:login' %}"
                            class="btn btn-outline-dark ps-lg-3 pe-lg-3 ms-lg-5">Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<main class="content">
    <!--    from top content name changed to header-->
    {% block topcontent %}
    <header class="main-header-back-img">
        <div class="container-lg padding-for-header-text">
            <div class="header-text">
                <h1 class="text-light">Cybersecurity</h1>
                <h5 class="text-light">Website for growing your knowledge about security in digital age</h5>
            </div>
        </div>
    </header>
    {% endblock %}
    {% block maincontent %}

    {% endblock %}
    <section class="events">
        {% block eventscontent %}
        <div class="container-lg">
            <h2 class="events-tile">Events</h2>
        </div>
        {% endblock %}
    </section>
    <section class="news">
        {% block newscontent %}
        <div class="container-lg">
            <h2 class="news-tile">News</h2>
        </div>
        {% endblock %}
    </section>
    {% block extracontent %} {% endblock %}
</main>
<footer class="navbar-fixed-bottom footer mt-auto py-3">
    <div class="container d-flex flex-wrap justify-content-between">
    	{% block socials %}
        <ul class="nav col justify-content-center justify-content-lg-start list-unstyled d-flex">
            <li class="ms-3"><a class="text-dark" href="https://www.instagram.com/alatoo.edu.kg/"><i class="bi bi-facebook h3"></i></a></li>
            <li class="ms-3"><a class="text-dark" href="https://www.instagram.com/alatoo.edu.kg/"><i class="bi bi-instagram h3"></i></a></li>
            <li class="ms-3"><a class="text-dark" href="https://www.instagram.com/alatoo.edu.kg/"><i class="bi bi-twitter-x h3"></i></a></li>
        </ul>
        {% endblock %}

        <ul class="nav justify-content-center list-unstyled">
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'home:home_page' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'members_area:member_page' %}">Members Area</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'user:login' %}">Members Area</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'home:for_parents' %}">For Parents</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'home:for_children' %}">For Children</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'home:about' %}">About</a>
            </li>
        </ul>
    </div>
</footer>
<!--bootstrap script load-->
<script src="js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<!--from internet-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>